In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [4]:
df = DataFrame(np.random.randint(0, 150, size=(100,5)), index=np.arange(100, 200), columns=['Python', 'En', 'Math', 'Physic', 'Chem'])
df

     Python   En  Math  Physic  Chem
100     113    8   125       3   109
101     147  117   144       7    82
102     110  128   136     118    23
103      95  100   110      48    84
104      83   71    84     105     0
105      83  100    93      93    92
106       5   19     3     105    95
107      99  115     3     126    93
108      51   54   125     106   149
109      48   30    50     146   124
110      20  124    36      33   122
111      45   89    98      23   130
112      28  108    94     137    81
113      59   49    28     126     9
114     139  124    47       8    48
115     112   79    43      41    77
116       8  118   146      98    98
117      10   94    17     111    68
118      44    7    71     108    63
119      89   27    67      47    39
120      27   82    76      34    97
121      63   74    11       9    57
122      73  142   137     138    15
123     123   54   149     138   136
124     134  148   133       6    38
125     107  120   121      54    97
126     147  133    87      58   132
127     102  146    38     113   148
128     101   78    80     106    95
129     148  149   108      31   144
..      ...  ...   ...     ...   ...
170     106   66    46     140    47
171      92   72   126      30    84
172     104    0    35      10    96
173     133   73    12     111    35
174      15   68    20      40    85
175      40  129    20      92    94
176      12   15   117      56     8
177      17   93    44      29   130
178     140  120   130      42   119
179     103  144   140      78     7
180      63  148    71     142    42
181      98  131    88     140   103
182      67   23    59      64    55
183      67  114    25     118   139
184      51   75   148      16   100
185     108  107    59     100     8
186      65  145     2      77    16
187     124  132   138     104    94
188      55   44    74     142    74
189      34  132    99      78    70
190      68   64    17       6    96
191       5   98    56      52   120
192     147  123   147      47   139
193     141   26   118      82   132
194     144   92   112      89    81
195     132  126   119     109    81
196     141  131    92      96    23
197      91   95     4      68    74
198      39   62   128      35   130
199      21   83    98      79   123

[100 rows x 5 columns]

In [5]:
df.isnull().any()

Python    False
En        False
Math      False
Physic    False
Chem      False
dtype: bool

In [6]:
df.notnull().all()

Python    True
En        True
Math      True
Physic    True
Chem      True
dtype: bool

In [7]:
100 * 5

500

In [8]:
for i in range(50):
    index = np.random.randint(100,200,size=1)[0]
    cols = df.columns
    col = np.random.choice(cols)
    df.loc[index, col] = None

In [9]:
for i in range(20):
    index = np.random.randint(100,200,size=1)[0]
    cols = df.columns
    col = np.random.choice(cols)
    df.loc[index, col] = np.NAN
df

     Python     En   Math  Physic   Chem
100   113.0    NaN  125.0     3.0  109.0
101   147.0  117.0  144.0     7.0   82.0
102   110.0  128.0  136.0   118.0    NaN
103    95.0    NaN  110.0    48.0   84.0
104    83.0   71.0   84.0   105.0    0.0
105     NaN  100.0   93.0    93.0   92.0
106     5.0   19.0    3.0   105.0   95.0
107     NaN  115.0    NaN   126.0   93.0
108    51.0   54.0    NaN     NaN  149.0
109     NaN   30.0   50.0     NaN  124.0
110    20.0  124.0   36.0    33.0  122.0
111    45.0   89.0   98.0    23.0  130.0
112     NaN  108.0    NaN   137.0   81.0
113    59.0   49.0   28.0   126.0    9.0
114   139.0  124.0   47.0     NaN   48.0
115   112.0   79.0   43.0     NaN   77.0
116     8.0  118.0    NaN    98.0   98.0
117    10.0   94.0   17.0   111.0   68.0
118    44.0    7.0   71.0   108.0   63.0
119    89.0   27.0   67.0     NaN   39.0
120    27.0   82.0   76.0     NaN   97.0
121    63.0   74.0   11.0     NaN   57.0
122    73.0  142.0  137.0   138.0   15.0
123   123.0    NaN    NaN   138.0  136.0
124   134.0  148.0  133.0     6.0    NaN
125     NaN  120.0    NaN    54.0   97.0
126     NaN  133.0   87.0    58.0  132.0
127   102.0  146.0   38.0   113.0  148.0
128   101.0   78.0   80.0     NaN   95.0
129   148.0  149.0  108.0    31.0    NaN
..      ...    ...    ...     ...    ...
170   106.0   66.0   46.0   140.0   47.0
171    92.0   72.0  126.0     NaN   84.0
172     NaN    0.0   35.0    10.0   96.0
173   133.0   73.0   12.0   111.0   35.0
174    15.0   68.0   20.0    40.0   85.0
175    40.0    NaN   20.0     NaN   94.0
176    12.0   15.0  117.0    56.0    8.0
177     NaN   93.0   44.0    29.0  130.0
178   140.0  120.0  130.0    42.0  119.0
179   103.0  144.0  140.0    78.0    NaN
180     NaN  148.0   71.0   142.0    NaN
181    98.0  131.0   88.0   140.0  103.0
182    67.0   23.0   59.0    64.0   55.0
183    67.0  114.0   25.0   118.0  139.0
184    51.0   75.0    NaN    16.0  100.0
185   108.0  107.0   59.0   100.0    8.0
186    65.0  145.0    2.0    77.0   16.0
187   124.0  132.0  138.0   104.0    NaN
188     NaN   44.0   74.0   142.0   74.0
189    34.0  132.0   99.0    78.0   70.0
190    68.0   64.0   17.0     NaN   96.0
191     5.0    NaN   56.0    52.0  120.0
192     NaN  123.0    NaN    47.0  139.0
193   141.0   26.0    NaN    82.0  132.0
194   144.0   92.0  112.0    89.0    NaN
195   132.0  126.0  119.0   109.0    NaN
196   141.0  131.0   92.0     NaN   23.0
197    91.0   95.0    4.0    68.0   74.0
198    39.0   62.0  128.0    35.0  130.0
199    21.0   83.0   98.0    79.0  123.0

[100 rows x 5 columns]

In [10]:
df.isnull().any()

Python    True
En        True
Math      True
Physic    True
Chem      True
dtype: bool

In [11]:
df.isnull().sum()

Python    18
En         7
Math      11
Physic    19
Chem      14
dtype: int64

In [12]:
df2 = df.copy()

In [13]:
df2.isnull().any()

Python    True
En        True
Math      True
Physic    True
Chem      True
dtype: bool

In [14]:
df2.isnull().sum()

Python    18
En         7
Math      11
Physic    19
Chem      14
dtype: int64

In [15]:
df2.fillna(value=100)

     Python     En   Math  Physic   Chem
100   113.0  100.0  125.0     3.0  109.0
101   147.0  117.0  144.0     7.0   82.0
102   110.0  128.0  136.0   118.0  100.0
103    95.0  100.0  110.0    48.0   84.0
104    83.0   71.0   84.0   105.0    0.0
105   100.0  100.0   93.0    93.0   92.0
106     5.0   19.0    3.0   105.0   95.0
107   100.0  115.0  100.0   126.0   93.0
108    51.0   54.0  100.0   100.0  149.0
109   100.0   30.0   50.0   100.0  124.0
110    20.0  124.0   36.0    33.0  122.0
111    45.0   89.0   98.0    23.0  130.0
112   100.0  108.0  100.0   137.0   81.0
113    59.0   49.0   28.0   126.0    9.0
114   139.0  124.0   47.0   100.0   48.0
115   112.0   79.0   43.0   100.0   77.0
116     8.0  118.0  100.0    98.0   98.0
117    10.0   94.0   17.0   111.0   68.0
118    44.0    7.0   71.0   108.0   63.0
119    89.0   27.0   67.0   100.0   39.0
120    27.0   82.0   76.0   100.0   97.0
121    63.0   74.0   11.0   100.0   57.0
122    73.0  142.0  137.0   138.0   15.0
123   123.0  100.0  100.0   138.0  136.0
124   134.0  148.0  133.0     6.0  100.0
125   100.0  120.0  100.0    54.0   97.0
126   100.0  133.0   87.0    58.0  132.0
127   102.0  146.0   38.0   113.0  148.0
128   101.0   78.0   80.0   100.0   95.0
129   148.0  149.0  108.0    31.0  100.0
..      ...    ...    ...     ...    ...
170   106.0   66.0   46.0   140.0   47.0
171    92.0   72.0  126.0   100.0   84.0
172   100.0    0.0   35.0    10.0   96.0
173   133.0   73.0   12.0   111.0   35.0
174    15.0   68.0   20.0    40.0   85.0
175    40.0  100.0   20.0   100.0   94.0
176    12.0   15.0  117.0    56.0    8.0
177   100.0   93.0   44.0    29.0  130.0
178   140.0  120.0  130.0    42.0  119.0
179   103.0  144.0  140.0    78.0  100.0
180   100.0  148.0   71.0   142.0  100.0
181    98.0  131.0   88.0   140.0  103.0
182    67.0   23.0   59.0    64.0   55.0
183    67.0  114.0   25.0   118.0  139.0
184    51.0   75.0  100.0    16.0  100.0
185   108.0  107.0   59.0   100.0    8.0
186    65.0  145.0    2.0    77.0   16.0
187   124.0  132.0  138.0   104.0  100.0
188   100.0   44.0   74.0   142.0   74.0
189    34.0  132.0   99.0    78.0   70.0
190    68.0   64.0   17.0   100.0   96.0
191     5.0  100.0   56.0    52.0  120.0
192   100.0  123.0  100.0    47.0  139.0
193   141.0   26.0  100.0    82.0  132.0
194   144.0   92.0  112.0    89.0  100.0
195   132.0  126.0  119.0   109.0  100.0
196   141.0  131.0   92.0   100.0   23.0
197    91.0   95.0    4.0    68.0   74.0
198    39.0   62.0  128.0    35.0  130.0
199    21.0   83.0   98.0    79.0  123.0

[100 rows x 5 columns]

In [16]:
df2.mean()

Python    83.414634
En        88.182796
Math      74.269663
Physic    71.629630
Chem      78.593023
dtype: float64

In [17]:
df3 = df2.fillna(value=df2.mean())
df3.astype(np.int16)

     Python   En  Math  Physic  Chem
100     113   88   125       3   109
101     147  117   144       7    82
102     110  128   136     118    78
103      95   88   110      48    84
104      83   71    84     105     0
105      83  100    93      93    92
106       5   19     3     105    95
107      83  115    74     126    93
108      51   54    74      71   149
109      83   30    50      71   124
110      20  124    36      33   122
111      45   89    98      23   130
112      83  108    74     137    81
113      59   49    28     126     9
114     139  124    47      71    48
115     112   79    43      71    77
116       8  118    74      98    98
117      10   94    17     111    68
118      44    7    71     108    63
119      89   27    67      71    39
120      27   82    76      71    97
121      63   74    11      71    57
122      73  142   137     138    15
123     123   88    74     138   136
124     134  148   133       6    78
125      83  120    74      54    97
126      83  133    87      58   132
127     102  146    38     113   148
128     101   78    80      71    95
129     148  149   108      31    78
..      ...  ...   ...     ...   ...
170     106   66    46     140    47
171      92   72   126      71    84
172      83    0    35      10    96
173     133   73    12     111    35
174      15   68    20      40    85
175      40   88    20      71    94
176      12   15   117      56     8
177      83   93    44      29   130
178     140  120   130      42   119
179     103  144   140      78    78
180      83  148    71     142    78
181      98  131    88     140   103
182      67   23    59      64    55
183      67  114    25     118   139
184      51   75    74      16   100
185     108  107    59     100     8
186      65  145     2      77    16
187     124  132   138     104    78
188      83   44    74     142    74
189      34  132    99      78    70
190      68   64    17      71    96
191       5   88    56      52   120
192      83  123    74      47   139
193     141   26    74      82   132
194     144   92   112      89    78
195     132  126   119     109    78
196     141  131    92      71    23
197      91   95     4      68    74
198      39   62   128      35   130
199      21   83    98      79   123

[100 rows x 5 columns]

In [18]:
nd = np.random.randint(0, 20, size=10)
nd

array([15, 16, 16,  7,  9,  0,  6,  5,  0,  3])

In [19]:
nd.sort()
nd

array([ 0,  0,  3,  5,  6,  7,  9, 15, 16, 16])

In [21]:
np.median(nd)

6.5

In [23]:
df2.median()
df4 = df2.fillna(df2.median())
df4

     Python     En   Math  Physic   Chem
100   113.0   92.0  125.0     3.0  109.0
101   147.0  117.0  144.0     7.0   82.0
102   110.0  128.0  136.0   118.0   84.0
103    95.0   92.0  110.0    48.0   84.0
104    83.0   71.0   84.0   105.0    0.0
105    90.0  100.0   93.0    93.0   92.0
106     5.0   19.0    3.0   105.0   95.0
107    90.0  115.0   74.0   126.0   93.0
108    51.0   54.0   74.0    67.0  149.0
109    90.0   30.0   50.0    67.0  124.0
110    20.0  124.0   36.0    33.0  122.0
111    45.0   89.0   98.0    23.0  130.0
112    90.0  108.0   74.0   137.0   81.0
113    59.0   49.0   28.0   126.0    9.0
114   139.0  124.0   47.0    67.0   48.0
115   112.0   79.0   43.0    67.0   77.0
116     8.0  118.0   74.0    98.0   98.0
117    10.0   94.0   17.0   111.0   68.0
118    44.0    7.0   71.0   108.0   63.0
119    89.0   27.0   67.0    67.0   39.0
120    27.0   82.0   76.0    67.0   97.0
121    63.0   74.0   11.0    67.0   57.0
122    73.0  142.0  137.0   138.0   15.0
123   123.0   92.0   74.0   138.0  136.0
124   134.0  148.0  133.0     6.0   84.0
125    90.0  120.0   74.0    54.0   97.0
126    90.0  133.0   87.0    58.0  132.0
127   102.0  146.0   38.0   113.0  148.0
128   101.0   78.0   80.0    67.0   95.0
129   148.0  149.0  108.0    31.0   84.0
..      ...    ...    ...     ...    ...
170   106.0   66.0   46.0   140.0   47.0
171    92.0   72.0  126.0    67.0   84.0
172    90.0    0.0   35.0    10.0   96.0
173   133.0   73.0   12.0   111.0   35.0
174    15.0   68.0   20.0    40.0   85.0
175    40.0   92.0   20.0    67.0   94.0
176    12.0   15.0  117.0    56.0    8.0
177    90.0   93.0   44.0    29.0  130.0
178   140.0  120.0  130.0    42.0  119.0
179   103.0  144.0  140.0    78.0   84.0
180    90.0  148.0   71.0   142.0   84.0
181    98.0  131.0   88.0   140.0  103.0
182    67.0   23.0   59.0    64.0   55.0
183    67.0  114.0   25.0   118.0  139.0
184    51.0   75.0   74.0    16.0  100.0
185   108.0  107.0   59.0   100.0    8.0
186    65.0  145.0    2.0    77.0   16.0
187   124.0  132.0  138.0   104.0   84.0
188    90.0   44.0   74.0   142.0   74.0
189    34.0  132.0   99.0    78.0   70.0
190    68.0   64.0   17.0    67.0   96.0
191     5.0   92.0   56.0    52.0  120.0
192    90.0  123.0   74.0    47.0  139.0
193   141.0   26.0   74.0    82.0  132.0
194   144.0   92.0  112.0    89.0   84.0
195   132.0  126.0  119.0   109.0   84.0
196   141.0  131.0   92.0    67.0   23.0
197    91.0   95.0    4.0    68.0   74.0
198    39.0   62.0  128.0    35.0  130.0
199    21.0   83.0   98.0    79.0  123.0

[100 rows x 5 columns]

In [4]:
df = DataFrame(np.random.randint(0,150,size=(2000, 5)), index=np.arange(100, 2100), columns=['Python','En','Math','Physic','Chem'])
df

      Python   En  Math  Physic  Chem
100       92   26   119       8    86
101      112   14    10     118    32
102       95  146    37     129    77
103      105   55   143     104   125
104      107  135   131      68    12
105       91   33    88     122    15
106       56   38    43     143   123
107      124  121    68      87   127
108      133   68   127      54    20
109       63   88    61      62     8
110       75   91    27      54    76
111       93  144    88      37   115
112       78   94    28     100     2
113      146   42   118      54     3
114      101   86   137      34    35
115       25   16   119      97    38
116       70  147    91      94    49
117       23   84   146     104   142
118      131   30    73      38    18
119      145   15    58      89    15
120       76  103    82     128    38
121       74   43    64      88    71
122       54   29     0      20    13
123       99   10    15      95     6
124       42   79   129      64   139
125      102   67    90     135    32
126      133   34     3      25   103
127      109  134     7     112    29
128       40  120    42      35    45
129       57   13    18      24    26
...      ...  ...   ...     ...   ...
2070       5   64    74     114   133
2071     114   91    55      54   105
2072     136    4    13      43    59
2073     125   32   108      89   142
2074     122  118    47      83    56
2075     109   44    73     100    13
2076      39  120    14       4    34
2077      35  120   145      53    58
2078      40  122    44      56    53
2079     131   99    76      60    71
2080      73   83    31     144    18
2081     133  121   143      95   116
2082      56    6   119      50    32
2083      42   65   137      75   121
2084      77   94   103      39   138
2085      98  101   128      31   112
2086       7   41    75     134    42
2087     102   19    16     140    96
2088      90  114   119      13    17
2089     130   40   148      77    66
2090     140    7    67     116   122
2091      80   47   102      68   148
2092     137    9   126       2    49
2093      48  118   128      74   102
2094      86   25   103     135    83
2095      11  105   100      88    35
2096      67   16   129      90    43
2097     129   11   111     134    91
2098      13   88     6      63    21
2099      83   31    99      81    85

[2000 rows x 5 columns]

In [5]:
for i in range(1000):
    index = np.random.randint(100, 2100, size=1)[0]
    cols = df.columns
    col = np.random.choice(cols)
    df.loc[index, col] = None

In [6]:
df.isnull().sum()

Python    190
En        197
Math      195
Physic    186
Chem      187
dtype: int64

In [7]:
df.head()

     Python     En   Math  Physic   Chem
100    92.0   26.0  119.0     8.0   86.0
101   112.0   14.0   10.0   118.0   32.0
102     NaN  146.0   37.0   129.0   77.0
103   105.0   55.0  143.0   104.0  125.0
104   107.0  135.0  131.0    68.0   12.0

In [8]:
df.tail()

      Python     En   Math  Physic  Chem
2095    11.0  105.0  100.0    88.0  35.0
2096    67.0   16.0  129.0    90.0  43.0
2097   129.0   11.0  111.0   134.0   NaN
2098    13.0   88.0    6.0    63.0  21.0
2099    83.0   31.0   99.0    81.0  85.0

In [9]:
df['Python'].unique()

array([ 92., 112.,  nan, 105., 107.,  91.,  56., 124., 133.,  63.,  75.,
        93.,  78., 101.,  70.,  23., 131., 145.,  76.,  74.,  99.,  42.,
       102.,  40.,  57.,  79.,  46., 108.,   0., 126.,  13.,  62., 121.,
         4.,  71.,  16.,  19.,  10.,  81.,  35.,  22.,  53., 129., 104.,
        44.,   1.,  96.,  88.,   7.,  25., 140.,  55.,   5.,  72., 118.,
        24., 114.,  68.,  60.,  86., 141.,  66., 138.,  95.,  97.,  80.,
        90.,  77.,  38., 115., 127.,  47., 135.,  28.,  31., 110.,  73.,
        15., 117., 130.,  65.,  45., 139., 122.,   2.,  59.,   3.,  11.,
        18.,  85.,  14.,   6.,  30., 123.,  98.,  12., 142.,  52.,  21.,
        48.,  87.,  26., 113., 109.,  82., 100.,  49.,  51., 149.,  69.,
         8.,  37., 106.,  41., 137., 111.,  36., 103., 128., 147.,  43.,
       134.,  54.,  20., 120.,  50.,  58.,  94.,  89.,  29.,   9.,  39.,
        34., 144., 125., 136., 146., 148., 119.,  64.,  83.,  27.,  84.,
        67., 132.,  17., 143.,  33.,  32., 116.,  61.])

In [10]:
df['Python'].value_counts()

73.0     22
80.0     22
149.0    21
35.0     21
115.0    19
124.0    19
90.0     19
5.0      18
37.0     18
1.0      17
129.0    17
13.0     17
76.0     17
144.0    16
138.0    16
72.0     16
4.0      16
38.0     16
130.0    15
121.0    15
10.0     15
92.0     15
65.0     15
15.0     15
14.0     15
107.0    15
24.0     15
114.0    15
86.0     15
145.0    15
         ..
132.0     9
17.0      9
20.0      9
2.0       9
110.0     9
26.0      9
67.0      9
64.0      9
34.0      8
131.0     8
89.0      8
52.0      8
61.0      8
87.0      8
100.0     8
137.0     8
60.0      8
68.0      8
71.0      8
49.0      8
148.0     7
125.0     7
123.0     6
62.0      6
69.0      6
78.0      6
43.0      6
33.0      5
19.0      5
143.0     5
Name: Python, Length: 150, dtype: int64

In [11]:
en = df['En'].value_counts()
en

121.0    20
124.0    19
16.0     19
73.0     19
94.0     18
54.0     18
125.0    18
115.0    18
103.0    17
32.0     17
95.0     17
1.0      17
42.0     17
61.0     16
53.0     16
106.0    16
105.0    16
113.0    16
24.0     16
0.0      16
62.0     15
15.0     15
58.0     15
128.0    15
146.0    15
147.0    15
63.0     15
22.0     15
88.0     15
99.0     15
         ..
17.0      9
47.0      9
116.0     9
46.0      9
6.0       9
57.0      9
129.0     8
69.0      8
139.0     8
90.0      8
51.0      8
127.0     8
112.0     8
10.0      8
13.0      8
79.0      8
133.0     8
148.0     7
4.0       7
144.0     7
18.0      7
38.0      7
23.0      7
89.0      6
43.0      6
20.0      5
33.0      5
49.0      5
114.0     5
132.0     5
Name: En, Length: 150, dtype: int64

In [12]:
en.index[0]

121.0

In [13]:
s = df.median()
print(s, type(s))

Python    76.0
En        75.0
Math      74.0
Physic    75.0
Chem      72.0
dtype: float64 <class 'pandas.core.series.Series'>